// Purpose: Operate authenticated local application workflows with explicit errors and downloadable artifacts.
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=new URLSearchParams(location.hash.slice(1));let token=hash.get('token')??sessionStorage.getItem('app-token')??'';
if(hash.has('token')){sessionStorage.setItem('app-token',token);history.replaceState(null,'',location.pathname);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(95000)});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
async function run(fn){$('#error').textContent='';document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){$('#error').textContent=e.message;}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function download(name,data,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('#login').onsubmit=e=>{e.preventDefault();token=$('#token').value;sessionStorage.setItem('app-token',token);run(refresh);};
$('#example').onclick=()=>run(async()=>{const {content}=await api('example');await importSource(content,'example');});
$('#file').onchange=()=>run(async()=>{const f=$('#file').files[0];if(!f||f.size>3000000)throw Error('Fichier inférieur à 3 Mo requis');await importSource(await f.text(),f.name);});

let current,nodeId;
async function refresh(){const w=await api('workspace');$('#login').hidden=true;$('#mode').textContent=w.mode==='synthetic'?'DÉMO · réponses simulées':w.mode==='live'?'Jev · appels facturables':'Clé Jev requise pour comparer';if(!current&&w.migrations.length)current=w.migrations[0];draw();}
function draw(){if(!current)return;const inspection=current.data.inspection;$('#inspection').innerHTML=`<h2>Nœuds de classification</h2><p>${esc(inspection.warning)}</p><label>Nœud<select id="nodes">${inspection.nodes.map(n=>`<option value="${esc(n.id)}" ${!n.eligible?'disabled':''}>${esc(n.title)}${n.eligible?'':' · incompatible'}</option>`).join('')}</select></label>${inspection.nodes.filter(n=>!n.eligible).map(n=>`<p>${esc(n.title)} : ${esc(n.reasons.join('; '))}</p>`).join('')}<button id="migrate" class="primary">Préparer le changement</button><div id="patch"></div>`;nodeId=$('#nodes').value;$('#nodes').onchange=()=>{nodeId=$('#nodes').value;$('#patch').innerHTML='';$('#comparison').innerHTML='';};$('#migrate').onclick=()=>run(async()=>{const result=await api('migrate',{id:current.id,nodeId,sourceFingerprint:inspection.sourceFingerprint});$('#patch').innerHTML=`<h3>Changement proposé</h3><pre>${esc(JSON.stringify(result.patch,null,2))}</pre><button id="save-yaml">Exporter le workflow YAML</button><button id="save-patch">Exporter le patch JSON</button>`;$('#save-yaml').onclick=()=>download('workflow-jev.yml',result.yaml,'text/yaml');$('#save-patch').onclick=()=>download('migration-patch.json',result);});}
async function importSource(content){current=await api('import',{content});$('#comparison').innerHTML='';await refresh();}
$('#compare').onclick=()=>run(async()=>{if(!current||!nodeId)throw Error('Importez et sélectionnez un nœud compatible');const report=await api('compare',{id:current.id,nodeId,cases:JSON.parse($('#cases').value),maxCalls:Number($('#budget').value)});$('#comparison').innerHTML=`<p>${report.data.disagreements} désaccord(s) · ${report.data.failures} erreur(s) · ${report.data.calls} appel(s)</p><pre>${esc(JSON.stringify(report.data.results,null,2))}</pre><button id="download-report">Exporter le rapport</button>`;$('#download-report').onclick=()=>download('migration-comparison.json',report.data);});
run(refresh);
